import { MenuItem } from "@/types";

export const MENU_ITEMS: MenuItem[] = [
  // Starters
  {
    id: "s1",
    name: "Wagyu Beef Tartare",
    description: "Hand-cut A5 Wagyu, quail egg yolk, truffle aioli, crispy shallots, sourdough chips.",
    price: 3800,
    category: "Starters",
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "s2",
    name: "Lobster Bisque",
    description: "Classic French style bisque, butter-poached Maine lobster claw, chervil oil.",
    price: 2800,
    category: "Starters",
    image_url: "https://images.unsplash.com/photo-1548943487-a2e4143fa9ce?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: true,
  },
  {
    id: "s3",
    name: "Sri Lankan Crab Cakes",
    description: "Negombo lagoon crab, spiced mango chutney, coconut foam, micro coriander.",
    price: 3200,
    category: "Starters",
    image_url: "https://images.unsplash.com/photo-1559841644-08984562005a?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "s4",
    name: "Burrata & Heirloom Tomato",
    description: "Imported Italian creamy burrata, basil pesto, balsamic reduction, pine nuts.",
    price: 4500,
    category: "Starters",
    image_url: "https://images.unsplash.com/photo-1608897013039-b2bf59af1cb0?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },

  // Mains
  {
    id: "m1",
    name: "Truffle Lobster Risotto",
    description: "Creamy arborio rice, fresh Maine lobster, shaved black truffle, aged parmesan.",
    price: 6500,
    category: "Mains",
    image_url: "https://images.unsplash.com/photo-1626203004838-8e658e38ee05?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: true,
  },
  {
    id: "m2",
    name: "Wagyu Beef Wellington",
    description: "Premium A5 Wagyu wrapped in mushroom duxelles and crisp puff pastry.",
    price: 12500,
    category: "Mains",
    image_url: "https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: true,
  },
  {
    id: "m3",
    name: "Black Cod Miso",
    description: "Den miso glazed Chilean sea bass, pickled ginger sprout, yuzu beurre blanc.",
    price: 8500,
    category: "Mains",
    image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "m4",
    name: "Ceylon Spiced Duck Breast",
    description: "Pan-seared duck, sweet potato purée, roasted baby carrots, dark cherry jus.",
    price: 7200,
    category: "Mains",
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },

  // Desserts
  {
    id: "d1",
    name: "Gold Leaf Chocolate Tart",
    description: "Valrhona dark chocolate ganache, hazelnut praline, 24k edible gold.",
    price: 2500,
    category: "Desserts",
    image_url: "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: true,
  },
  {
    id: "d2",
    name: "Deconstructed Pavlova",
    description: "Crispy meringue, passionfruit curd, fresh seasonal berries, vanilla chantilly.",
    price: 1800,
    category: "Desserts",
    image_url: "https://images.unsplash.com/photo-1549488344-c18ec517e0b5?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "d3",
    name: "Watalappan Mille-Feuille",
    description: "Sri Lankan palm treacle custard layered between crisp puff pastry, cashew brittle.",
    price: 2000,
    category: "Desserts",
    image_url: "https://images.unsplash.com/photo-1563805041-76846175b9f7?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "d4",
    name: "Matcha Tiramisu",
    description: "Ceremonial grade matcha ladyfingers, mascarpone cream, white chocolate dust.",
    price: 2200,
    category: "Desserts",
    image_url: "https://images.unsplash.com/photo-1510626176961-4b57d4fbad03?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },

  // Drinks
  {
    id: "b1",
    name: "Sorriso Food Signature Cocktail",
    description: "Arrack, pressed pineapple, cardamom syrup, lime, smoked cinnamon fog.",
    price: 2500,
    category: "Drinks",
    image_url: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: true,
  },
  {
    id: "b2",
    name: "Vintage Dom Perignon",
    description: "Glass of 2012 Vintage Champagne. Complex, brilliant, and floral.",
    price: 18000,
    category: "Drinks",
    image_url: "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "b3",
    name: "Artisan Kombucha",
    description: "House-fermented hibiscus and ginger craft kombucha.",
    price: 1200,
    category: "Drinks",
    image_url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
  {
    id: "b4",
    name: "Single Origin Ceylon Tea",
    description: "Hand-plucked Nuwara Eliya silver tips, brewed table-side.",
    price: 900,
    category: "Drinks",
    image_url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop",
    is_available: true,
    is_featured: false,
  },
];
